version: '3.7'

services:

  api:
    build:
      context: .
      network: host
    ports:
        - "9999:8000"
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - POSTGRES_HOST=restaurant_assistant
      - POSTGRES_PORT=5432
    env_file:
      - src/config/.env
    depends_on:
     - postgres


  postgres:
    hostname: restaurant_assistant
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
    env_file:
      - src/config/.env

volumes:
  postgres_data: